INSERT INTO TB_USERS (LOGIN, PASSWORD) VALUES ('ADMIN', '$2a$12$Kb/YWYqtQpTPi/hc/Mqi/.Xq4nU4y2A/t4H1z/pTgQ5CDlHno7ORq');

INSERT INTO TB_PLAYLISTS (NOME, DESCRICAO) VALUES ('Lista 1', 'Lista de musicas do Spotify');
INSERT INTO TB_SONGS (TITULO, ARTISTA, ALBUM, ANO, GENERO, PLAYLIST_ID) VALUES ('', '', '', '', '', 1);
INSERT INTO TB_SONGS (TITULO, ARTISTA, ALBUM, ANO, GENERO, PLAYLIST_ID) VALUES ('', '', '', '', '', 1);